linkPrefix = ""
compiler = "0.4.6+commit.2dabbdf0.Linux.g++"
name = "ipchain-contracts"
license = "ISC"
version = "1.0.0"
description = "Смарт контракты проекта IPCHAIN.RU"
homepage = "https://bitbucket.org/vitiko/ipc-chain#readme"
author = ""
buildTime = 2017-01-23T15:29:50.652Z
target = "scripts/doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/9445d59056058159ce25d7cd1643039523718553.tar.gz"
out = "docs"

[interaction]
network = "2"
providerUrl = "https://morden.infura.io/sign_up_to_get_a_hash"

[whitelist]

[whitelist.all]
abi = true
methods = true
bytecode = true
source = false

[whitelist.DigixMath]
source = true